name: bloc_gen
version: 1.0.1
author: Sahandevs <sahandevs@gmail.com>
description: >-
  Automatically generate BLoC patterns.
homepage: https://github.com/SahandAkbarzadeh/bloc_generator
environment:
  sdk: '>=2.1.1 <3.0.0'

dependencies:
  build: ^1.0.0
  source_gen: ^0.9.0
  bloc_generator_annotation: any
  dart_style: ^1.0.10

