name: bloc_generator
version: 1.0.0
author: Sahandevs <sahandevs@gmail.com>
description: >-
  Automatically generate BLoC patterns.
homepage: https://github.com/SahandAkbarzadeh/bloc_generator
environment:
  sdk: '>=2.1.1 <3.0.0'

dependencies:
  build: ^1.0.0
  source_gen: ^0.9.0
  bloc_generator_annotation: ^2.3.0
  dart_style: ^1.0.10

dependency_overrides:
  bloc_generator_annotation:
    path: ../bloc_generator_annotation