name: bloc_generator_annotation
version: 1.0.0
description: >-
  helper annotations for bloc_generator to work.
homepage: https://github.com/SahandAkbarzadeh/bloc_generator
author: Sahandevs <sahandevs@gmail.com>
environment:
  sdk: '>=2.1.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter